name: r5rs
language: Haskell2010

library:
  source-dirs: src
  dependencies:
    - base
    - array
    - parsec

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - base
    - r5rs
