name: r5rs
license: BSD3
version: 0.0.0.0
language: Haskell2010

library:
  source-dirs: src
  dependencies:
    - base
    - array
    - mtl
    - parsec

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - base
    - r5rs
